[package]
name = "day3"
version = "0.1.0"
authors = ["icealtria <icealtria@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
regex = "1.11.1"

[profile.release]
opt-level = "s"